import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const manifest = JSON.parse(fs.readFileSync("manifest.json", "utf8"));
const outDir = path.join("dist", manifest.id);
fs.mkdirSync(outDir, { recursive: true });

const assetsToCopy = ["manifest.json", "styles.css"];

function copyAssets() {
	for (const file of assetsToCopy) {
		if (fs.existsSync(file)) {
			fs.copyFileSync(file, path.join(outDir, file));
		}
	}
}

const copyAssetsPlugin = {
	name: "copy-assets",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyAssets();
				console.log(`[copy-assets] synced to ${outDir}/`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(outDir, "main.js"),
	plugins: [copyAssetsPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
